local set = vim.opt

set.encoding = 'utf-8' --default character encoding
set.mouse= ""
set.hidden = true
set.undofile = true
set.undodir = '$HOME/.vim/undo'
set.undolevels = 1000
set.undoreload = 10000
set.scrollback = 100000
set.lazyredraw = true
set.synmaxcol= 128
set.clipboard = set.clipboard + 'unnamed,unnamedplus'
set.number = true
set.shiftwidth = 2
set.shiftround = true
set.smarttab = true
set.autoindent = true 
set.copyindent = true 
set.smartindent = true
set.tabstop = 2 
set.softtabstop = 2
set.expandtab = true
set.shiftwidth = 2
set.hlsearch  = true
set.incsearch = true
set.ignorecase = true
set.smartcase = true
set.cursorline = true
set.title = true
set.synmaxcol = 150
set.lazyredraw = true
set.ttyfast = true
set.regexpengine = 1
set.splitbelow = true
set.splitright = true
set.spell = true
set.spelllang='en_gb'
-- set.noswapfile = true -- TODO what is this?
set.completeopt='menu,menuone,noselect'
-- s.t foldmethod=expr
set.foldexpr='nvim_treesitter#foldexpr()'
