# -*- mode: shell-script; -*-
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/bin"

# I want to title my shells by myself.
export DISABLE_AUTO_TITLE=true

# Load direnv
#eval "$(zsh)"
# eval "$(direnv hook zsh)"

# Load asdf
. $HOME/.asdf/asdf.sh

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zprofile_local ]] && source $HOME/.zprofile_local

# # Ask kitty to use config from ~/.config (even on MacOS)
# export KITTY_CONFIG_DIRECTORY="$HOME/.config/kitty"
