# FZF
export FZF_BASE='~/.fzf/bin/bin'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Use ripgrep as FZF's default search in order to respect .gitignore
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'

export EDITOR='nvim'
export VISUAL=$EDITOR

export VIMCONFIG=~/.config/$EDITOR
export VIMDATA=~/.local/share/$EDITOR

# Powerlevel 9k bar config
POWERLEVEL9K_MODE='nerdfont-complete'

# gruvbox in shell
BASE16_SCHEME=gruvbox-dark-soft
BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-$BASE16_SCHEME.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Enable enable reverse search in zsh
bindkey -v
bindkey '^R' history-incremental-search-backward

# Load local zshrc
[[ -f $HOME/.zshrc_local ]] && source $HOME/.zshrc_local

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"


plugins=(git elixir fzf zsh-autosuggestions zsh-syntax-highlighting)

source ~/.oh-my-zsh/plugins/git/git.plugin.zsh
source $ZSH/oh-my-zsh.sh

export SSH_KEY_PATH="~/.ssh/*"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# aliases
alias vim=$EDITOR
alias vi=$EDITOR
alias e=$EDITOR
alias zshconfig="e ~/.zshrc"
alias ohmyzsh="e ~/.oh-my-zsh"
alias crontab="VIM_CRONTAB=true crontab"
