#ZSH
export ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="dallas"
plugins=(git elixir)
source $ZSH/oh-my-zsh.sh

# With this, apps using $EDITOR will use nvim .
export EDITOR='nvim'
export VISUAL=$EDITOR

export VIMCONFIG=~/.config/$EDITOR
export VIMDATA=~/.local/share/$EDITOR

# Aliases
alias vim=$EDITOR
alias vi=$EDITOR
alias e=$EDITOR

# FZF

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Use ripgrep as FZF's default search in order to respect .gitignore
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Powerlevel 9k bar config

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)

# source "$HOME/.config/nvim/plugged/gruvbox/gruvbox_256palette_osx.sh"
# gruvbox in shell
BASE16_SCHEME=gruvbox-light-medium
BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-$BASE16_SCHEME.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL


# Load local zshrc
[[ -f $HOME/.zshrc_local ]] && source $HOME/.zshrc_local
