
# Source Prezto

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# GPG

if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi

# FZF

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Powerlevel 9k bar config

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)

# Custom Aliases

function fe() {
  $EDITOR $(git ls-files -co --exclude-standard | peco)
}

# Git Status Interactive - Not Added
function gsina {
  git status --porcelain \
  | awk '{ if (substr($0, 0, 2) ~ /^[ ?].$/) print $0 }' \
  | peco \
  | awk '{ print "'`git rev-parse --show-toplevel`'/"$2 }'
}

alias g='git'
alias ga='git add'
alias gai='gsina | xargs git add'
alias gaip='gsina | xargs -o git add -p'
alias gb='git branch'
alias gbdi='git branch | peco | xargs git branch -d'
alias gc='git commit'
alias gco='git checkout'
alias gcoi="git branch --all | peco | sed 's/remotes\/origin\///g' | xargs git checkout"
alias gd='git diff'
alias gdi='gsina | xargs -o git diff'
alias gf='git fetch --all'
alias gh='git stash'
alias ghl='git stash list'
alias ghp='git stash pop'
alias git='noglob git'
alias gl='git log'
alias gp='git push'
alias gpo='git push origin'
alias gpot='git push origin --tags'
alias gpuo='git push -u origin `git rev-parse --abbrev-ref HEAD`'
alias gr='git reset'
alias gri='gsina | git reset'
alias gs='git status'
alias gull='git pull'
alias grc='git rev-list -n 1 HEAD --'

